# Generated by Django 4.1.5 on 2023-02-08 11:40

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Science Fiction', 'Science Fiction'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Crime', 'Crime'), ('Action', 'Action')], max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
